name: powerdart
description: >-
  Compute the Power Spectral Density (PSD) on Dart.
  This package runs everywhere dart runs.
version: 0.0.2
homepage: https://github.com/Supercaly/powerdart
repository: https://github.com/Supercaly/powerdart
issue_tracker: https://github.com/Supercaly/powerdart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # Dependency for complex numbers
  complex: ^0.5.0

dev_dependencies:
  test: any